### ISSUE TITLE
Issues with vagrant up

### ISSUE THREAD

**Issue by BenjaminJoerger** [OXID-eSales/oxvm_eshop#41]
Running `vagrant up` gives an error with OS Win 10
```
default: dpkg: error processing package libssl1.1:amd64 (--configure):
    default:  installed libssl1.1:amd64 package post-installation script subprocess returned error exit status 10
    default: Setting up python-enum34 (1.1.6-2) ...
    default: dpkg: dependency problems prevent configuration of python-cryptography:
    default:  python-cryptography depends on libssl1.1 (>= 1.1.1); however:
    default:   Package libssl1.1:amd64 is not configured yet.
    default:
    default: dpkg: error processing package python-cryptography (--configure):
    default:  dependency problems - leaving unconfigured
```

Looks like an error in libssl https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1832919

I could solve it doing a dist upgrade
```
vagrant ssh
sudo apt-get update
sudo apt-get upgrade
exit
vagrant provision
```
